### ISSUE TITLE
How can I use ipmi to get disk info

### ISSUE THREAD

**Issue by Kotodian** [gebn/bmc#32]

**Comment by gebn** [comment]
Hi @Kotodian, the library currently supports analogue sensors, so if you have any SDRs pertaining to disks with these, it will be able to pull them. The sensors available will depend on your hardware.

**Comment by Kotodian** [comment]
> Hi @Kotodian, the library currently supports analogue sensors, so if you have any SDRs pertaining to disks with these, it will be able to pull them. The sensors available will depend on your hardware.

thank you.if I want to get the hardware's Info,what tool you recommend?thank you very much

**Comment by gebn** [comment]
I use [`ipmitool`](https://linux.die.net/man/1/ipmitool), in particular the `sdr elist` command.

**Comment by Kotodian** [comment]
> I use [`ipmitool`](https://linux.die.net/man/1/ipmitool), in particular the `sdr elist` command.

it only provide the fan's rotating speed.Can it provide other information?  thank you.

**Comment by gebn** [comment]
I’m afraid not - the SDR is like a menu of sensors, and the BMC can only retrieve readings for those it knows about. You can derive new values manually, e.g. by multiplying fan speed by a constant to get the volume of air moved (which some BMCs expose directly).

**Comment by Kotodian** [comment]
> I’m afraid not - the SDR is like a menu of sensors, and the BMC can only retrieve readings for those it knows about. You can derive new values manually, e.g. by multiplying fan speed by a constant to get the volume of air moved (which some BMCs expose directly).

I really have no idea to calculate the power by fan speed
