### ISSUE TITLE
implementing an IPMI v2.0 simulator

### ISSUE THREAD

**Issue by jacobweinstock** [gebn/bmc#37]
Hey @gebn , really like and appreciate this library. Thanks for all the work!

I'm trying to write an IPMI v2.0 simulator and wanted to see if you could help point me in the direction of any good documentation, besides the [spec](https://www.intel.com/content/dam/www/public/us/en/documents/specification-updates/ipmi-intelligent-platform-mgt-interface-spec-2nd-gen-v2-0-spec-update.pdf), by chance? 

I'm following the general pattern of the v1.5 simulator found [here](https://github.com/vmware/goipmi/blob/master/simulator.go), but having trouble following the v2 spec. Any help or guidance would be really appreciated!

**Comment by gebn** [comment]
By simulator, are you looking to implement the wire protocol, for testing a standalone IPMI client? I'd have another go at the spec (it is the spec after all), and fall back on any of the usual clients (ipmitool, openipmi, freeipmi etc.) to see what they send and expect back. Wireshark certainly helped me when developing this library. You'll have to start by implementing RAKP, but can then focus on just the in-session commands you need. Hopefully adding logging to this library can help you!
