### ISSUE TITLE
boot device support

### ISSUE THREAD

**Issue by jacobweinstock** [gebn/bmc#39]
Hi, I don't see boot device support in this library. This fork has added boot device support. https://github.com/baas-project/bmc/tree/GetSystemBootOptionsCmd. I'm not affiliated with this fork but I'm wondering if boot device support is something you'd be open to accepting? If so, I could see about contacting the maintainers to gauge interest in contributing here.

**Comment by gebn** [comment]
Definitely open to reviewing PRs!
