### ISSUE TITLE
Dell BMC: Insufficient Privileges although MaxPrivilegeLevel is set

### ISSUE THREAD

**Issue by oliverpool** [gebn/bmc#44]
Hi,

first of all, thank you so much for this great library!

---

## Issue

We want to control some chassis (for instance `power-up`).

We currently face an issue similar to #38, where we get a `Insufficient Privileges` reply (even though the `MaxPrivilegeLevel` is correctly set):
```go
	sess, err := machine.NewSession(ctx, &bmc.SessionOpts{
		Username:          c.Username,
		Password:          []byte(c.Password),
		MaxPrivilegeLevel: ipmi.PrivilegeLevelOperator,
	})
```
If we issue the same command from `ipmi-chassis` (FreeIPMI package), everything works fine:
```
ipmi-chassis -D LAN_2_0 -h XXX.XXX.XXX.XXX -u user -p secret -l user --chassis-control=POWER-UP
```

It seems that `ipmi-chassis` sends a `0x3b - Set Session Privilege Level` command at the start, which is not available in this library yet.

According to [the spec](https://www.intel.com/content/dam/www/public/us/en/documents/specification-updates/ipmi-intelligent-platform-mgt-interface-spec-2nd-gen-v2-0-spec-update.pdf), page 88
> All sessions start off at User Level privilege. It is necessary to issue a Set Session Privilege to raise the
operating privilege level before commands that required higher privilege can be executed. The maximum
operating privilege for a session is determined by Privilege Limits that are set both for the user and for the
overall channel. The more restrictive setting of the User Privilege Limit and the Channel Privilege Limit sets
the maximum operating privilege available for a session.

So I think this command should be added to the library and automatically sent if a command needs a privilege higher than `User`.

What to do you think about this ?

---

## .pcap analysis

To reach this conclusion, we captured the packets sent by this library and `ipmi-chassis` using `tcpdump`. We then analyzed this .pcap file, however the commands are encrypted.

Since we know the password (and since the IPMI protocal has no forward-secrecy - we are lucky :-), we were able to very slowly decipher some packets using this guide: https://github.com/beingj/hash/blob/master/RMCP%2B%20Packet%20decrypt%20and%20authcode.org . It works, but involves a lot of manual (and error-prone) steps and gives us only the payload as `[]byte` (which we now need to decode to the proper command and arguments).

To ease such analyze, we thought about writing a pcap analyzer, using github.com/google/gopacket/pcap and your library (this would also partially address #5 & #18, if integrated in this library ;).
In order to achieve this, we must be able to decode `RAKP Message 1` packets, which is not available yet (PR is coming ;).

I now have a working prototype, up to the `key` construction.

However I am now struggling with `gopacket` to add the freshly made `decipherLayer` available to the gopacket analyzer.

If you think that such `pcap` analysis tool would be a nice addition to you repo, I can make a draft PR to show you where I am stuck (this is my first time working with github.com/google/gopacket/pcap)

**Comment by oliverpool** [comment]
I can confirm that the `PrivilegeLevel` is the issue.

If I set `MaxPrivilegeLevel: ipmi.PrivilegeLevelOperator` and then retrieve the `SessionInfo`, I get `User`.
```go
	sess, err := machine.NewSession(ctx, &bmc.SessionOpts{
		Username:          c.Username,
		Password:          []byte(c.Password),
		MaxPrivilegeLevel: ipmi.PrivilegeLevelOperator,
	})
	if err != nil {
		return err
	}
	defer sess.Close(ctx)

	info, err := sess.GetSessionInfo(ctx, &ipmi.GetSessionInfoReq{})
	if err != nil {
		return err
	}
	fmt.Println("Current privliege:", info.PrivilegeLevel) // displays `Current privliege: User`
```

**Comment by gebn** [comment]
Sounds very reasonable. This was next up on my commands to implement, so thank you for doing it! I think a pcap analysis tool would be a useful addition for developers to debug problematic packet captures, exactly as you saw. I'll take a look at the PR.

**Comment by oliverpool** [comment]
Alright, I will try to cleanup the code a bit and make a draft PR, for you to take a look at the code.
