### ISSUE TITLE
Use non-zero exit codes for failures in cmd/describe/

### ISSUE THREAD

**Issue by lukeyeager** [gebn/bmc#53]
It would be nice to use `log.Fatal()` here (and in the 3 other spots in that function which are treated as irrecoverable errors):
https://github.com/gebn/bmc/blob/30abb01db32e5ac3e95094bcff6be9a86747fcc3/cmd/describe/main.go#L81-L82

When testing new versions, I like to loop through my BMCs to see whether this library can connect to them w/o errors (FYI, as of https://github.com/gebn/bmc/pull/51#issuecomment-1230515334, they all work! 🎉). I'll work on getting approval for sending PRs in the future.

**Comment by gebn** [comment]
`log.Fatal()` is suboptimal as it ignores `defer`red logic. I agree with your point though. The nicest way I can think of is to create a wrapper function:

```go
func main() {
	if err := realMain(context.Background()); err != nil {
		log.Fatal(err)
	}
}

func realMain(ctx context.Context) error {
	// current main() here, deferring clean-up logic and returning fatal errors
}
```
