### ISSUE TITLE
not able to execute linux command on bmc instance

### ISSUE THREAD

**Issue by gangwgr** [gebn/bmc#54]
I want to execute date comand bmc instance but not able to do. Can you please help?

I tried like this 
type DateCommand struct{}

func (c *DateCommand) Name() string {
	return "date"
}

func (c *DateCommand) Operation() *ipmi.Operation {
	return &ipmi.Operation{}
}

func (c *DateCommand) Request() gopacket.SerializableLayer {
	return nil
}

func (c *DateCommand) Response() gopacket.DecodingLayer {
	return nil
}
func (upirdu *Upirdusession) ExecuteCmdOnUPIbaremetalInstance() error {
	argBMCAddr := upirdu.BMCHOSTNAME
	username := upirdu.BMCUSERNAME
	password := upirdu.BMCPASSWORD
	cmd := &DateCommand{}

	ctx, cancel := context.WithTimeout(context.Background(), time.Second*5)
	defer cancel()
	machine, err := bmc.Dial(ctx, argBMCAddr)
	if err != nil {
		o.Expect(err).NotTo(o.HaveOccurred())
	}
	defer machine.Close()
	e2e.Logf("connected to %v over IPMI v%v", machine.Address(), machine.Version())
	sess, err := machine.NewSession(ctx, &bmc.SessionOpts{
		Username:          username,
		Password:          []byte(password),
		MaxPrivilegeLevel: ipmi.PrivilegeLevelOperator,
	})
	if err != nil {
		o.Expect(err).NotTo(o.HaveOccurred())
	}
	defer sess.Close(ctx)

	oy, err := sess.SendCommand(ctx, cmd)
	if err == nil {
		e2e.Logf("tttt :: %s :: %v", oy, oy.String())
	}
	return err
}

**Comment by gebn** [comment]
IPMI cannot be used to run command line utilities unfortunately - it is completely separate from the host, which is one of its features. Only commands in the [spec](https://www.intel.com/content/dam/www/public/us/en/documents/specification-updates/ipmi-intelligent-platform-mgt-interface-spec-2nd-gen-v2-0-spec-update.pdf) can be executed.
